### ISSUE TITLE
Support `apiKey` security scheme

### ISSUE THREAD

**Issue by umar-ahmed** [jlalmes/trpc-openapi#239]
Seems like the security scheme is currently hard-coded to bearer token: https://github.com/jlalmes/trpc-openapi/blob/fab401af82f3b734831da60c8a00fae2fea27008/src/generator/index.ts#L36-L41

I'd like to use an API key as a custom header instead:

```yaml
  securitySchemes:
    api_key:
      type: apiKey
      name: "X-API-KEY"
      in: header
```

My current workaround is to modify the generated openapi document manually to remove the bearer one and insert what I want:

```js
  // Remove bearer auth from the openapi document
  delete openApiDocument.components?.securitySchemes?.Authorization;

  // Insert API key auth into the openapi document
  openApiDocument.components!.securitySchemes!.api_key = {
    type: "apiKey",
    name: "X-API-KEY",
    in: "header",
  };
```
